### ISSUE TITLE
Gladiatus

### ISSUE THREAD

**Issue by Zecifer** [GreatApo/GithubDesktopGitPath#1]
Would it possible that you are some other devs who knows gladiatus try to code a new gamefeature (like new dungeons in britannia)? maybe the gameforge would implement those stuff or at least think about it. because i guess the gameforge wouldnt improve anything in this game the next 10000 years. all devs there bussy with the new gf stuff.

best regards

**Comment by GreatApo** [comment]
Gameforge has that game still running just because they don't have to update it, I don't think that will work on the game again

**Comment by Zecifer** [comment]
what wont work?

ofc they dont have to. they just puplishing new server and make money out of it.

how long would you think it takes to code an update including 6 new dungeons in brittania for 1 prof. java skripter?

**Comment by GreatApo** [comment]
> what wont work?
> 
> ofc they dont have to. they just puplishing new server and make money out of it.
> 
> how long would you think it takes to code an update including 6 new dungeons in brittania for 1 prof. java skripter?

They can probably do it within a week with a developer and a graphics designer. I don't think that's the problem, they have just moved to other projects/games.
